language: go
go:
  - 1.7
  - 1.8
  - master
sudo: required
group: deprecated-2017Q2
services:
  - docker
before_install:
  # - docker run -d -p 10101:10101 pilosa/pilosa:v0.4.0
  - go get github.com/mattn/goveralls      
  - curl -O https://storage.googleapis.com/pilosa/pilosa-attrs
  - chmod +x pilosa-attrs
  - ./pilosa-attrs server &
addons:
  apt:
    sources:
      - sourceline: 'ppa:masterminds/glide'
    packages:
      - glide
script:
  - glide up && $HOME/gopath/bin/goveralls -service=travis-ci -ignore "internal/public.pb.go" -flags="-tags=integration"
