language: go
go:
  - "1.9"
  - "1.10"
  - master
env:
  matrix:
    - GOARCH=386 PILOSA_VERSION=master
    - GOARCH=386 PILOSA_VERSION=v1.0
    - GOARCH=amd64 PILOSA_VERSION=master
    - GOARCH=amd64 PILOSA_VERSION=v1.0
install:
  - go get -u github.com/golang/dep/cmd/dep
script:
  - make test-all-race TESTFLAGS=-v
jobs:
  include:
    - stage: deploy
      script: go get github.com/mattn/goveralls && make cover TESTFLAGS=-v && $HOME/gopath/bin/goveralls -service=travis-ci -ignore "gopilosa_pbuf/public.pb.go" -coverprofile=build/coverage.out
      go: "1.10"
      env:
        - GOARCH=amd64 PILOSA_VERSION=master
stages:
  - test
  - deploy
