// Code generated by protoc-gen-go.
// source: gopilosa_pbuf/public.proto
// DO NOT EDIT!

/*
Package gopilosa_pbuf is a generated protocol buffer package.

It is generated from these files:
	gopilosa_pbuf/public.proto

It has these top-level messages:
	Row
	RowIdentifiers
	Pair
	FieldRow
	GroupCount
	ValCount
	ColumnAttrSet
	Attr
	AttrMap
	QueryRequest
	QueryResponse
	QueryResult
	ImportRequest
	ImportValueRequest
	TranslateKeysRequest
	TranslateKeysResponse
	ImportRoaringRequestView
	ImportRoaringRequest
*/
package gopilosa_pbuf

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Row struct {
	Columns []uint64 `protobuf:"varint,1,rep,packed,name=Columns" json:"Columns,omitempty"`
	Keys    []string `protobuf:"bytes,3,rep,name=Keys" json:"Keys,omitempty"`
	Attrs   []*Attr  `protobuf:"bytes,2,rep,name=Attrs" json:"Attrs,omitempty"`
}

func (m *Row) Reset()                    { *m = Row{} }
func (m *Row) String() string            { return proto.CompactTextString(m) }
func (*Row) ProtoMessage()               {}
func (*Row) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Row) GetColumns() []uint64 {
	if m != nil {
		return m.Columns
	}
	return nil
}

func (m *Row) GetKeys() []string {
	if m != nil {
		return m.Keys
	}
	return nil
}

func (m *Row) GetAttrs() []*Attr {
	if m != nil {
		return m.Attrs
	}
	return nil
}

type RowIdentifiers struct {
	Rows []uint64 `protobuf:"varint,1,rep,packed,name=Rows" json:"Rows,omitempty"`
	Keys []string `protobuf:"bytes,2,rep,name=Keys" json:"Keys,omitempty"`
}

func (m *RowIdentifiers) Reset()                    { *m = RowIdentifiers{} }
func (m *RowIdentifiers) String() string            { return proto.CompactTextString(m) }
func (*RowIdentifiers) ProtoMessage()               {}
func (*RowIdentifiers) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *RowIdentifiers) GetRows() []uint64 {
	if m != nil {
		return m.Rows
	}
	return nil
}

func (m *RowIdentifiers) GetKeys() []string {
	if m != nil {
		return m.Keys
	}
	return nil
}

type Pair struct {
	ID    uint64 `protobuf:"varint,1,opt,name=ID" json:"ID,omitempty"`
	Key   string `protobuf:"bytes,3,opt,name=Key" json:"Key,omitempty"`
	Count uint64 `protobuf:"varint,2,opt,name=Count" json:"Count,omitempty"`
}

func (m *Pair) Reset()                    { *m = Pair{} }
func (m *Pair) String() string            { return proto.CompactTextString(m) }
func (*Pair) ProtoMessage()               {}
func (*Pair) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Pair) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Pair) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Pair) GetCount() uint64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type FieldRow struct {
	Field  string `protobuf:"bytes,1,opt,name=Field" json:"Field,omitempty"`
	RowID  uint64 `protobuf:"varint,2,opt,name=RowID" json:"RowID,omitempty"`
	RowKey string `protobuf:"bytes,3,opt,name=RowKey" json:"RowKey,omitempty"`
}

func (m *FieldRow) Reset()                    { *m = FieldRow{} }
func (m *FieldRow) String() string            { return proto.CompactTextString(m) }
func (*FieldRow) ProtoMessage()               {}
func (*FieldRow) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *FieldRow) GetField() string {
	if m != nil {
		return m.Field
	}
	return ""
}

func (m *FieldRow) GetRowID() uint64 {
	if m != nil {
		return m.RowID
	}
	return 0
}

func (m *FieldRow) GetRowKey() string {
	if m != nil {
		return m.RowKey
	}
	return ""
}

type GroupCount struct {
	Group []*FieldRow `protobuf:"bytes,1,rep,name=Group" json:"Group,omitempty"`
	Count uint64      `protobuf:"varint,2,opt,name=Count" json:"Count,omitempty"`
}

func (m *GroupCount) Reset()                    { *m = GroupCount{} }
func (m *GroupCount) String() string            { return proto.CompactTextString(m) }
func (*GroupCount) ProtoMessage()               {}
func (*GroupCount) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *GroupCount) GetGroup() []*FieldRow {
	if m != nil {
		return m.Group
	}
	return nil
}

func (m *GroupCount) GetCount() uint64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type ValCount struct {
	Val   int64 `protobuf:"varint,1,opt,name=Val" json:"Val,omitempty"`
	Count int64 `protobuf:"varint,2,opt,name=Count" json:"Count,omitempty"`
}

func (m *ValCount) Reset()                    { *m = ValCount{} }
func (m *ValCount) String() string            { return proto.CompactTextString(m) }
func (*ValCount) ProtoMessage()               {}
func (*ValCount) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ValCount) GetVal() int64 {
	if m != nil {
		return m.Val
	}
	return 0
}

func (m *ValCount) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type ColumnAttrSet struct {
	ID    uint64  `protobuf:"varint,1,opt,name=ID" json:"ID,omitempty"`
	Key   string  `protobuf:"bytes,3,opt,name=Key" json:"Key,omitempty"`
	Attrs []*Attr `protobuf:"bytes,2,rep,name=Attrs" json:"Attrs,omitempty"`
}

func (m *ColumnAttrSet) Reset()                    { *m = ColumnAttrSet{} }
func (m *ColumnAttrSet) String() string            { return proto.CompactTextString(m) }
func (*ColumnAttrSet) ProtoMessage()               {}
func (*ColumnAttrSet) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *ColumnAttrSet) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *ColumnAttrSet) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *ColumnAttrSet) GetAttrs() []*Attr {
	if m != nil {
		return m.Attrs
	}
	return nil
}

type Attr struct {
	Key         string  `protobuf:"bytes,1,opt,name=Key" json:"Key,omitempty"`
	Type        uint64  `protobuf:"varint,2,opt,name=Type" json:"Type,omitempty"`
	StringValue string  `protobuf:"bytes,3,opt,name=StringValue" json:"StringValue,omitempty"`
	IntValue    int64   `protobuf:"varint,4,opt,name=IntValue" json:"IntValue,omitempty"`
	BoolValue   bool    `protobuf:"varint,5,opt,name=BoolValue" json:"BoolValue,omitempty"`
	FloatValue  float64 `protobuf:"fixed64,6,opt,name=FloatValue" json:"FloatValue,omitempty"`
}

func (m *Attr) Reset()                    { *m = Attr{} }
func (m *Attr) String() string            { return proto.CompactTextString(m) }
func (*Attr) ProtoMessage()               {}
func (*Attr) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *Attr) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Attr) GetType() uint64 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *Attr) GetStringValue() string {
	if m != nil {
		return m.StringValue
	}
	return ""
}

func (m *Attr) GetIntValue() int64 {
	if m != nil {
		return m.IntValue
	}
	return 0
}

func (m *Attr) GetBoolValue() bool {
	if m != nil {
		return m.BoolValue
	}
	return false
}

func (m *Attr) GetFloatValue() float64 {
	if m != nil {
		return m.FloatValue
	}
	return 0
}

type AttrMap struct {
	Attrs []*Attr `protobuf:"bytes,1,rep,name=Attrs" json:"Attrs,omitempty"`
}

func (m *AttrMap) Reset()                    { *m = AttrMap{} }
func (m *AttrMap) String() string            { return proto.CompactTextString(m) }
func (*AttrMap) ProtoMessage()               {}
func (*AttrMap) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *AttrMap) GetAttrs() []*Attr {
	if m != nil {
		return m.Attrs
	}
	return nil
}

type QueryRequest struct {
	Query           string   `protobuf:"bytes,1,opt,name=Query" json:"Query,omitempty"`
	Shards          []uint64 `protobuf:"varint,2,rep,packed,name=Shards" json:"Shards,omitempty"`
	ColumnAttrs     bool     `protobuf:"varint,3,opt,name=ColumnAttrs" json:"ColumnAttrs,omitempty"`
	Remote          bool     `protobuf:"varint,5,opt,name=Remote" json:"Remote,omitempty"`
	ExcludeRowAttrs bool     `protobuf:"varint,6,opt,name=ExcludeRowAttrs" json:"ExcludeRowAttrs,omitempty"`
	ExcludeColumns  bool     `protobuf:"varint,7,opt,name=ExcludeColumns" json:"ExcludeColumns,omitempty"`
}

func (m *QueryRequest) Reset()                    { *m = QueryRequest{} }
func (m *QueryRequest) String() string            { return proto.CompactTextString(m) }
func (*QueryRequest) ProtoMessage()               {}
func (*QueryRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *QueryRequest) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

func (m *QueryRequest) GetShards() []uint64 {
	if m != nil {
		return m.Shards
	}
	return nil
}

func (m *QueryRequest) GetColumnAttrs() bool {
	if m != nil {
		return m.ColumnAttrs
	}
	return false
}

func (m *QueryRequest) GetRemote() bool {
	if m != nil {
		return m.Remote
	}
	return false
}

func (m *QueryRequest) GetExcludeRowAttrs() bool {
	if m != nil {
		return m.ExcludeRowAttrs
	}
	return false
}

func (m *QueryRequest) GetExcludeColumns() bool {
	if m != nil {
		return m.ExcludeColumns
	}
	return false
}

type QueryResponse struct {
	Err            string           `protobuf:"bytes,1,opt,name=Err" json:"Err,omitempty"`
	Results        []*QueryResult   `protobuf:"bytes,2,rep,name=Results" json:"Results,omitempty"`
	ColumnAttrSets []*ColumnAttrSet `protobuf:"bytes,3,rep,name=ColumnAttrSets" json:"ColumnAttrSets,omitempty"`
}

func (m *QueryResponse) Reset()                    { *m = QueryResponse{} }
func (m *QueryResponse) String() string            { return proto.CompactTextString(m) }
func (*QueryResponse) ProtoMessage()               {}
func (*QueryResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *QueryResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func (m *QueryResponse) GetResults() []*QueryResult {
	if m != nil {
		return m.Results
	}
	return nil
}

func (m *QueryResponse) GetColumnAttrSets() []*ColumnAttrSet {
	if m != nil {
		return m.ColumnAttrSets
	}
	return nil
}

type QueryResult struct {
	Type           uint32          `protobuf:"varint,6,opt,name=Type" json:"Type,omitempty"`
	Row            *Row            `protobuf:"bytes,1,opt,name=Row" json:"Row,omitempty"`
	N              uint64          `protobuf:"varint,2,opt,name=N" json:"N,omitempty"`
	Pairs          []*Pair         `protobuf:"bytes,3,rep,name=Pairs" json:"Pairs,omitempty"`
	Changed        bool            `protobuf:"varint,4,opt,name=Changed" json:"Changed,omitempty"`
	ValCount       *ValCount       `protobuf:"bytes,5,opt,name=ValCount" json:"ValCount,omitempty"`
	RowIDs         []uint64        `protobuf:"varint,7,rep,packed,name=RowIDs" json:"RowIDs,omitempty"`
	GroupCounts    []*GroupCount   `protobuf:"bytes,8,rep,name=GroupCounts" json:"GroupCounts,omitempty"`
	RowIdentifiers *RowIdentifiers `protobuf:"bytes,9,opt,name=RowIdentifiers" json:"RowIdentifiers,omitempty"`
}

func (m *QueryResult) Reset()                    { *m = QueryResult{} }
func (m *QueryResult) String() string            { return proto.CompactTextString(m) }
func (*QueryResult) ProtoMessage()               {}
func (*QueryResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *QueryResult) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *QueryResult) GetRow() *Row {
	if m != nil {
		return m.Row
	}
	return nil
}

func (m *QueryResult) GetN() uint64 {
	if m != nil {
		return m.N
	}
	return 0
}

func (m *QueryResult) GetPairs() []*Pair {
	if m != nil {
		return m.Pairs
	}
	return nil
}

func (m *QueryResult) GetChanged() bool {
	if m != nil {
		return m.Changed
	}
	return false
}

func (m *QueryResult) GetValCount() *ValCount {
	if m != nil {
		return m.ValCount
	}
	return nil
}

func (m *QueryResult) GetRowIDs() []uint64 {
	if m != nil {
		return m.RowIDs
	}
	return nil
}

func (m *QueryResult) GetGroupCounts() []*GroupCount {
	if m != nil {
		return m.GroupCounts
	}
	return nil
}

func (m *QueryResult) GetRowIdentifiers() *RowIdentifiers {
	if m != nil {
		return m.RowIdentifiers
	}
	return nil
}

type ImportRequest struct {
	Index      string   `protobuf:"bytes,1,opt,name=Index" json:"Index,omitempty"`
	Field      string   `protobuf:"bytes,2,opt,name=Field" json:"Field,omitempty"`
	Shard      uint64   `protobuf:"varint,3,opt,name=Shard" json:"Shard,omitempty"`
	RowIDs     []uint64 `protobuf:"varint,4,rep,packed,name=RowIDs" json:"RowIDs,omitempty"`
	ColumnIDs  []uint64 `protobuf:"varint,5,rep,packed,name=ColumnIDs" json:"ColumnIDs,omitempty"`
	RowKeys    []string `protobuf:"bytes,7,rep,name=RowKeys" json:"RowKeys,omitempty"`
	ColumnKeys []string `protobuf:"bytes,8,rep,name=ColumnKeys" json:"ColumnKeys,omitempty"`
	Timestamps []int64  `protobuf:"varint,6,rep,packed,name=Timestamps" json:"Timestamps,omitempty"`
}

func (m *ImportRequest) Reset()                    { *m = ImportRequest{} }
func (m *ImportRequest) String() string            { return proto.CompactTextString(m) }
func (*ImportRequest) ProtoMessage()               {}
func (*ImportRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *ImportRequest) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

func (m *ImportRequest) GetField() string {
	if m != nil {
		return m.Field
	}
	return ""
}

func (m *ImportRequest) GetShard() uint64 {
	if m != nil {
		return m.Shard
	}
	return 0
}

func (m *ImportRequest) GetRowIDs() []uint64 {
	if m != nil {
		return m.RowIDs
	}
	return nil
}

func (m *ImportRequest) GetColumnIDs() []uint64 {
	if m != nil {
		return m.ColumnIDs
	}
	return nil
}

func (m *ImportRequest) GetRowKeys() []string {
	if m != nil {
		return m.RowKeys
	}
	return nil
}

func (m *ImportRequest) GetColumnKeys() []string {
	if m != nil {
		return m.ColumnKeys
	}
	return nil
}

func (m *ImportRequest) GetTimestamps() []int64 {
	if m != nil {
		return m.Timestamps
	}
	return nil
}

type ImportValueRequest struct {
	Index      string   `protobuf:"bytes,1,opt,name=Index" json:"Index,omitempty"`
	Field      string   `protobuf:"bytes,2,opt,name=Field" json:"Field,omitempty"`
	Shard      uint64   `protobuf:"varint,3,opt,name=Shard" json:"Shard,omitempty"`
	ColumnIDs  []uint64 `protobuf:"varint,5,rep,packed,name=ColumnIDs" json:"ColumnIDs,omitempty"`
	ColumnKeys []string `protobuf:"bytes,7,rep,name=ColumnKeys" json:"ColumnKeys,omitempty"`
	Values     []int64  `protobuf:"varint,6,rep,packed,name=Values" json:"Values,omitempty"`
}

func (m *ImportValueRequest) Reset()                    { *m = ImportValueRequest{} }
func (m *ImportValueRequest) String() string            { return proto.CompactTextString(m) }
func (*ImportValueRequest) ProtoMessage()               {}
func (*ImportValueRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *ImportValueRequest) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

func (m *ImportValueRequest) GetField() string {
	if m != nil {
		return m.Field
	}
	return ""
}

func (m *ImportValueRequest) GetShard() uint64 {
	if m != nil {
		return m.Shard
	}
	return 0
}

func (m *ImportValueRequest) GetColumnIDs() []uint64 {
	if m != nil {
		return m.ColumnIDs
	}
	return nil
}

func (m *ImportValueRequest) GetColumnKeys() []string {
	if m != nil {
		return m.ColumnKeys
	}
	return nil
}

func (m *ImportValueRequest) GetValues() []int64 {
	if m != nil {
		return m.Values
	}
	return nil
}

type TranslateKeysRequest struct {
	Index string   `protobuf:"bytes,1,opt,name=Index" json:"Index,omitempty"`
	Field string   `protobuf:"bytes,2,opt,name=Field" json:"Field,omitempty"`
	Keys  []string `protobuf:"bytes,3,rep,name=Keys" json:"Keys,omitempty"`
}

func (m *TranslateKeysRequest) Reset()                    { *m = TranslateKeysRequest{} }
func (m *TranslateKeysRequest) String() string            { return proto.CompactTextString(m) }
func (*TranslateKeysRequest) ProtoMessage()               {}
func (*TranslateKeysRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *TranslateKeysRequest) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

func (m *TranslateKeysRequest) GetField() string {
	if m != nil {
		return m.Field
	}
	return ""
}

func (m *TranslateKeysRequest) GetKeys() []string {
	if m != nil {
		return m.Keys
	}
	return nil
}

type TranslateKeysResponse struct {
	IDs []uint64 `protobuf:"varint,3,rep,packed,name=IDs" json:"IDs,omitempty"`
}

func (m *TranslateKeysResponse) Reset()                    { *m = TranslateKeysResponse{} }
func (m *TranslateKeysResponse) String() string            { return proto.CompactTextString(m) }
func (*TranslateKeysResponse) ProtoMessage()               {}
func (*TranslateKeysResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *TranslateKeysResponse) GetIDs() []uint64 {
	if m != nil {
		return m.IDs
	}
	return nil
}

type ImportRoaringRequestView struct {
	Name string `protobuf:"bytes,1,opt,name=Name" json:"Name,omitempty"`
	Data []byte `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (m *ImportRoaringRequestView) Reset()                    { *m = ImportRoaringRequestView{} }
func (m *ImportRoaringRequestView) String() string            { return proto.CompactTextString(m) }
func (*ImportRoaringRequestView) ProtoMessage()               {}
func (*ImportRoaringRequestView) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *ImportRoaringRequestView) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ImportRoaringRequestView) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type ImportRoaringRequest struct {
	Clear bool                        `protobuf:"varint,1,opt,name=Clear" json:"Clear,omitempty"`
	Views []*ImportRoaringRequestView `protobuf:"bytes,2,rep,name=views" json:"views,omitempty"`
}

func (m *ImportRoaringRequest) Reset()                    { *m = ImportRoaringRequest{} }
func (m *ImportRoaringRequest) String() string            { return proto.CompactTextString(m) }
func (*ImportRoaringRequest) ProtoMessage()               {}
func (*ImportRoaringRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *ImportRoaringRequest) GetClear() bool {
	if m != nil {
		return m.Clear
	}
	return false
}

func (m *ImportRoaringRequest) GetViews() []*ImportRoaringRequestView {
	if m != nil {
		return m.Views
	}
	return nil
}

func init() {
	proto.RegisterType((*Row)(nil), "gopilosa_pbuf.Row")
	proto.RegisterType((*RowIdentifiers)(nil), "gopilosa_pbuf.RowIdentifiers")
	proto.RegisterType((*Pair)(nil), "gopilosa_pbuf.Pair")
	proto.RegisterType((*FieldRow)(nil), "gopilosa_pbuf.FieldRow")
	proto.RegisterType((*GroupCount)(nil), "gopilosa_pbuf.GroupCount")
	proto.RegisterType((*ValCount)(nil), "gopilosa_pbuf.ValCount")
	proto.RegisterType((*ColumnAttrSet)(nil), "gopilosa_pbuf.ColumnAttrSet")
	proto.RegisterType((*Attr)(nil), "gopilosa_pbuf.Attr")
	proto.RegisterType((*AttrMap)(nil), "gopilosa_pbuf.AttrMap")
	proto.RegisterType((*QueryRequest)(nil), "gopilosa_pbuf.QueryRequest")
	proto.RegisterType((*QueryResponse)(nil), "gopilosa_pbuf.QueryResponse")
	proto.RegisterType((*QueryResult)(nil), "gopilosa_pbuf.QueryResult")
	proto.RegisterType((*ImportRequest)(nil), "gopilosa_pbuf.ImportRequest")
	proto.RegisterType((*ImportValueRequest)(nil), "gopilosa_pbuf.ImportValueRequest")
	proto.RegisterType((*TranslateKeysRequest)(nil), "gopilosa_pbuf.TranslateKeysRequest")
	proto.RegisterType((*TranslateKeysResponse)(nil), "gopilosa_pbuf.TranslateKeysResponse")
	proto.RegisterType((*ImportRoaringRequestView)(nil), "gopilosa_pbuf.ImportRoaringRequestView")
	proto.RegisterType((*ImportRoaringRequest)(nil), "gopilosa_pbuf.ImportRoaringRequest")
}

func init() { proto.RegisterFile("gopilosa_pbuf/public.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 875 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0x5f, 0x8f, 0xdb, 0x44,
	0x10, 0xd7, 0xc6, 0x4e, 0xe2, 0x4c, 0x2e, 0x47, 0xb5, 0x1c, 0xc5, 0x9c, 0x0e, 0x64, 0x59, 0x08,
	0xdc, 0x07, 0x0e, 0x29, 0xed, 0x03, 0x12, 0x02, 0x89, 0x36, 0x57, 0x14, 0x55, 0x9c, 0xe8, 0xdc,
	0x29, 0x4f, 0x08, 0xb4, 0xd7, 0x6c, 0xaf, 0x16, 0x8e, 0xd7, 0xd8, 0x6b, 0xd2, 0x7c, 0x18, 0xde,
	0x79, 0xe0, 0x83, 0xf0, 0x35, 0x78, 0xe6, 0x4b, 0xa0, 0x9d, 0xf5, 0x9e, 0x1d, 0x5f, 0xcb, 0x3f,
	0xf5, 0x6d, 0x7e, 0x33, 0xb3, 0xe3, 0xf9, 0xcd, 0xbf, 0x04, 0x8e, 0xaf, 0x55, 0x91, 0x66, 0xaa,
	0x12, 0x3f, 0x14, 0x57, 0xf5, 0xf3, 0x4f, 0x8b, 0xfa, 0x2a, 0x4b, 0x9f, 0x9d, 0x16, 0xa5, 0xd2,
	0x8a, 0xcf, 0xf6, 0x6c, 0xf1, 0xf7, 0xe0, 0xa1, 0xda, 0xf2, 0x10, 0xc6, 0x8f, 0x54, 0x56, 0x6f,
	0xf2, 0x2a, 0x64, 0x91, 0x97, 0xf8, 0xe8, 0x20, 0xe7, 0xe0, 0x3f, 0x91, 0xbb, 0x2a, 0xf4, 0x22,
	0x2f, 0x99, 0x20, 0xc9, 0xfc, 0x1e, 0x0c, 0xbf, 0xd2, 0xba, 0xac, 0xc2, 0x41, 0xe4, 0x25, 0xd3,
	0xf9, 0xdb, 0xa7, 0x7b, 0x31, 0x4f, 0x8d, 0x0d, 0xad, 0x47, 0xfc, 0x19, 0x1c, 0xa2, 0xda, 0x2e,
	0xd7, 0x32, 0xd7, 0xe9, 0xf3, 0x54, 0x96, 0x14, 0x10, 0xd5, 0xd6, 0x7d, 0x87, 0xe4, 0x9b, 0x8f,
	0x0c, 0xda, 0x8f, 0xc4, 0x5f, 0x82, 0xff, 0xad, 0x48, 0x4b, 0x7e, 0x08, 0x83, 0xe5, 0x22, 0x64,
	0x11, 0x4b, 0x7c, 0x1c, 0x2c, 0x17, 0xfc, 0x0e, 0x78, 0x4f, 0xe4, 0x2e, 0xf4, 0x22, 0x96, 0x4c,
	0xd0, 0x88, 0xfc, 0x08, 0x86, 0x8f, 0x54, 0x9d, 0xeb, 0x70, 0x40, 0x4e, 0x16, 0xc4, 0xe7, 0x10,
	0x3c, 0x4e, 0x65, 0xb6, 0x36, 0xf4, 0x8e, 0x60, 0x48, 0x32, 0x85, 0x99, 0xa0, 0x05, 0x46, 0x6b,
	0x72, 0x5b, 0xb8, 0x77, 0x04, 0xf8, 0x5d, 0x18, 0xa1, 0xda, 0xb6, 0x9f, 0x68, 0x50, 0xfc, 0x14,
	0xe0, 0xeb, 0x52, 0xd5, 0x05, 0x45, 0xe7, 0x9f, 0xc0, 0x90, 0x10, 0xd1, 0x98, 0xce, 0xdf, 0xed,
	0x95, 0xc0, 0x7d, 0x19, 0xad, 0xd7, 0x6b, 0x52, 0x9c, 0x43, 0xb0, 0x12, 0x99, 0x0d, 0x78, 0x07,
	0xbc, 0x95, 0xc8, 0x28, 0x41, 0x0f, 0x8d, 0xb8, 0xff, 0xc6, 0x73, 0x6f, 0xbe, 0x83, 0x99, 0x6d,
	0x8d, 0xa9, 0xef, 0x85, 0xd4, 0xff, 0xa2, 0x3e, 0xff, 0xa1, 0x5d, 0xbf, 0x32, 0xf0, 0x8d, 0xe4,
	0xa2, 0xb0, 0x36, 0x0a, 0x07, 0xff, 0x72, 0x57, 0xc8, 0x86, 0x01, 0xc9, 0x3c, 0x82, 0xe9, 0x85,
	0x2e, 0xd3, 0xfc, 0x7a, 0x25, 0xb2, 0x5a, 0x36, 0xdf, 0xec, 0xaa, 0xf8, 0x31, 0x04, 0xcb, 0x5c,
	0x5b, 0xb3, 0x4f, 0x3c, 0x6e, 0x30, 0x3f, 0x81, 0xc9, 0x43, 0xa5, 0x32, 0x6b, 0x1c, 0x46, 0x2c,
	0x09, 0xb0, 0x55, 0xf0, 0x0f, 0x00, 0x1e, 0x67, 0x4a, 0x34, 0x6f, 0x47, 0x11, 0x4b, 0x18, 0x76,
	0x34, 0xf1, 0x03, 0x18, 0x9b, 0x4c, 0xbf, 0x11, 0x45, 0x4b, 0x90, 0xfd, 0x23, 0xc1, 0xdf, 0x19,
	0x1c, 0x3c, 0xad, 0x65, 0xb9, 0x43, 0xf9, 0x53, 0x2d, 0x2b, 0x6d, 0xaa, 0x4c, 0xd8, 0x8d, 0x06,
	0x01, 0x33, 0x04, 0x17, 0x2f, 0x44, 0xb9, 0xb6, 0x35, 0xf3, 0xb1, 0x41, 0x86, 0x70, 0x5b, 0xfd,
	0x8a, 0x08, 0x07, 0xd8, 0x55, 0xd1, 0xf8, 0xc8, 0x8d, 0xd2, 0x8e, 0x51, 0x83, 0x78, 0x02, 0x6f,
	0x9d, 0xbd, 0x7c, 0x96, 0xd5, 0x6b, 0x89, 0x6a, 0x6b, 0x5f, 0x8f, 0xc8, 0xa1, 0xaf, 0xe6, 0x1f,
	0xc1, 0x61, 0xa3, 0x72, 0x2b, 0x39, 0x26, 0xc7, 0x9e, 0x36, 0xfe, 0x85, 0xc1, 0xac, 0xa1, 0x52,
	0x15, 0x2a, 0xaf, 0xa4, 0x69, 0xda, 0x59, 0x59, 0xba, 0xa6, 0x9d, 0x95, 0x25, 0x7f, 0x00, 0x63,
	0x94, 0x55, 0x9d, 0x69, 0xd7, 0xfc, 0xe3, 0x5e, 0x6d, 0x5c, 0x80, 0x3a, 0xd3, 0xe8, 0x5c, 0xf9,
	0x02, 0x0e, 0xf7, 0x66, 0xcc, 0x6e, 0xff, 0x74, 0x7e, 0xd2, 0x7b, 0xbc, 0xe7, 0x84, 0xbd, 0x37,
	0xf1, 0x9f, 0x03, 0x98, 0x76, 0xc2, 0xdf, 0x0c, 0x90, 0xa1, 0x3d, 0x6b, 0x06, 0xe8, 0x43, 0x3a,
	0x3f, 0x94, 0xf1, 0x74, 0xce, 0x7b, 0xe1, 0xcd, 0xfe, 0xd0, 0x75, 0x3a, 0x00, 0x76, 0xde, 0xcc,
	0x1d, 0x3b, 0x37, 0xdd, 0x36, 0x87, 0xc1, 0x25, 0xd5, 0xef, 0xb6, 0xb1, 0xa1, 0xf5, 0xa0, 0xb3,
	0xf6, 0x42, 0xe4, 0xd7, 0x72, 0x4d, 0xc3, 0x17, 0xa0, 0x83, 0xfc, 0x7e, 0xbb, 0x7a, 0xd4, 0xa8,
	0xdb, 0x2b, 0xec, 0xcc, 0xd8, 0xee, 0xa8, 0x3d, 0x0d, 0xcb, 0x85, 0xe9, 0x08, 0x4d, 0x85, 0x45,
	0xfc, 0x73, 0x98, 0xb6, 0xa7, 0xa1, 0x0a, 0x03, 0xca, 0xeb, 0xbd, 0x5e, 0xbc, 0xd6, 0x03, 0xbb,
	0xde, 0xfc, 0xac, 0x7f, 0x21, 0xc3, 0x09, 0xe5, 0xf3, 0xfe, 0xed, 0x6a, 0x74, 0x9c, 0xb0, 0xf7,
	0x28, 0xfe, 0x83, 0xc1, 0x6c, 0xb9, 0x29, 0x54, 0xa9, 0x3b, 0x93, 0xbd, 0xcc, 0xd7, 0xf2, 0xa5,
	0x9b, 0x6c, 0x02, 0xed, 0x29, 0x1c, 0xf4, 0x4e, 0x21, 0x4d, 0x38, 0x4d, 0xb4, 0x8f, 0x16, 0x74,
	0xf8, 0xfa, 0x7b, 0x7c, 0x4f, 0x60, 0x62, 0x7b, 0x6d, 0x4c, 0x43, 0x32, 0xb5, 0x0a, 0x53, 0x74,
	0x7b, 0x32, 0x6d, 0x99, 0x26, 0xe8, 0xa0, 0x59, 0x69, 0xeb, 0x46, 0xc6, 0x80, 0x8c, 0x1d, 0x8d,
	0xb1, 0x5f, 0xa6, 0x1b, 0x59, 0x69, 0xb1, 0x29, 0xcc, 0x7a, 0x78, 0x89, 0x87, 0x1d, 0x4d, 0xfc,
	0x1b, 0x03, 0x6e, 0x39, 0xd2, 0x09, 0x78, 0x73, 0x44, 0xff, 0x9e, 0xd0, 0x7e, 0xda, 0xe3, 0x5b,
	0x69, 0xdf, 0x85, 0x11, 0xe5, 0xe3, 0x52, 0x6e, 0x50, 0xbc, 0x82, 0xa3, 0xcb, 0x52, 0xe4, 0x55,
	0x26, 0xb4, 0x34, 0x8e, 0xff, 0x27, 0xdf, 0x57, 0xfc, 0xfc, 0xc6, 0xf7, 0xe0, 0x9d, 0x5e, 0xdc,
	0x76, 0xff, 0x0d, 0x01, 0x8f, 0x08, 0x18, 0x31, 0x7e, 0x08, 0x61, 0x33, 0x14, 0x4a, 0x98, 0xa3,
	0xdc, 0xa4, 0xb0, 0x4a, 0xe5, 0xd6, 0x84, 0x3e, 0x17, 0x1b, 0xd9, 0x64, 0x41, 0xb2, 0xd1, 0x2d,
	0x84, 0x16, 0x94, 0xc3, 0x01, 0x92, 0x1c, 0xff, 0x08, 0x47, 0xaf, 0x8a, 0x41, 0xbf, 0x4f, 0x99,
	0x14, 0xf6, 0xde, 0x04, 0x68, 0x01, 0xff, 0x02, 0x86, 0x3f, 0xa7, 0x72, 0xeb, 0xee, 0xcd, 0xc7,
	0xbd, 0x29, 0x7e, 0x5d, 0x36, 0x68, 0x5f, 0x5d, 0x8d, 0xe8, 0x5f, 0xca, 0xfd, 0xbf, 0x02, 0x00,
	0x00, 0xff, 0xff, 0x84, 0xb9, 0x90, 0x2b, 0xc3, 0x08, 0x00, 0x00,
}
