// Code generated by protoc-gen-go.
// source: internal/public.proto
// DO NOT EDIT!

/*
Package internal is a generated protocol buffer package.

It is generated from these files:
	internal/public.proto

It has these top-level messages:
	Bitmap
	Pair
	Bit
	ColumnAttrSet
	Attr
	AttrMap
	QueryRequest
	QueryResponse
	QueryResult
	ImportRequest
*/
package internal

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Bitmap struct {
	Bits  []uint64 `protobuf:"varint,1,rep,packed,name=Bits" json:"Bits,omitempty"`
	Attrs []*Attr  `protobuf:"bytes,2,rep,name=Attrs" json:"Attrs,omitempty"`
}

func (m *Bitmap) Reset()                    { *m = Bitmap{} }
func (m *Bitmap) String() string            { return proto.CompactTextString(m) }
func (*Bitmap) ProtoMessage()               {}
func (*Bitmap) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Bitmap) GetBits() []uint64 {
	if m != nil {
		return m.Bits
	}
	return nil
}

func (m *Bitmap) GetAttrs() []*Attr {
	if m != nil {
		return m.Attrs
	}
	return nil
}

type Pair struct {
	Key   uint64 `protobuf:"varint,1,opt,name=Key" json:"Key,omitempty"`
	Count uint64 `protobuf:"varint,2,opt,name=Count" json:"Count,omitempty"`
}

func (m *Pair) Reset()                    { *m = Pair{} }
func (m *Pair) String() string            { return proto.CompactTextString(m) }
func (*Pair) ProtoMessage()               {}
func (*Pair) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Pair) GetKey() uint64 {
	if m != nil {
		return m.Key
	}
	return 0
}

func (m *Pair) GetCount() uint64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type Bit struct {
	RowID     uint64 `protobuf:"varint,1,opt,name=RowID" json:"RowID,omitempty"`
	ColumnID  uint64 `protobuf:"varint,2,opt,name=ColumnID" json:"ColumnID,omitempty"`
	Timestamp int64  `protobuf:"varint,3,opt,name=Timestamp" json:"Timestamp,omitempty"`
}

func (m *Bit) Reset()                    { *m = Bit{} }
func (m *Bit) String() string            { return proto.CompactTextString(m) }
func (*Bit) ProtoMessage()               {}
func (*Bit) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Bit) GetRowID() uint64 {
	if m != nil {
		return m.RowID
	}
	return 0
}

func (m *Bit) GetColumnID() uint64 {
	if m != nil {
		return m.ColumnID
	}
	return 0
}

func (m *Bit) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type ColumnAttrSet struct {
	ID    uint64  `protobuf:"varint,1,opt,name=ID" json:"ID,omitempty"`
	Attrs []*Attr `protobuf:"bytes,2,rep,name=Attrs" json:"Attrs,omitempty"`
}

func (m *ColumnAttrSet) Reset()                    { *m = ColumnAttrSet{} }
func (m *ColumnAttrSet) String() string            { return proto.CompactTextString(m) }
func (*ColumnAttrSet) ProtoMessage()               {}
func (*ColumnAttrSet) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ColumnAttrSet) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *ColumnAttrSet) GetAttrs() []*Attr {
	if m != nil {
		return m.Attrs
	}
	return nil
}

type Attr struct {
	Key         string  `protobuf:"bytes,1,opt,name=Key" json:"Key,omitempty"`
	Type        uint64  `protobuf:"varint,2,opt,name=Type" json:"Type,omitempty"`
	StringValue string  `protobuf:"bytes,3,opt,name=StringValue" json:"StringValue,omitempty"`
	IntValue    int64   `protobuf:"varint,4,opt,name=IntValue" json:"IntValue,omitempty"`
	BoolValue   bool    `protobuf:"varint,5,opt,name=BoolValue" json:"BoolValue,omitempty"`
	FloatValue  float64 `protobuf:"fixed64,6,opt,name=FloatValue" json:"FloatValue,omitempty"`
}

func (m *Attr) Reset()                    { *m = Attr{} }
func (m *Attr) String() string            { return proto.CompactTextString(m) }
func (*Attr) ProtoMessage()               {}
func (*Attr) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Attr) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Attr) GetType() uint64 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *Attr) GetStringValue() string {
	if m != nil {
		return m.StringValue
	}
	return ""
}

func (m *Attr) GetIntValue() int64 {
	if m != nil {
		return m.IntValue
	}
	return 0
}

func (m *Attr) GetBoolValue() bool {
	if m != nil {
		return m.BoolValue
	}
	return false
}

func (m *Attr) GetFloatValue() float64 {
	if m != nil {
		return m.FloatValue
	}
	return 0
}

type AttrMap struct {
	Attrs []*Attr `protobuf:"bytes,1,rep,name=Attrs" json:"Attrs,omitempty"`
}

func (m *AttrMap) Reset()                    { *m = AttrMap{} }
func (m *AttrMap) String() string            { return proto.CompactTextString(m) }
func (*AttrMap) ProtoMessage()               {}
func (*AttrMap) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *AttrMap) GetAttrs() []*Attr {
	if m != nil {
		return m.Attrs
	}
	return nil
}

type QueryRequest struct {
	Query       string   `protobuf:"bytes,1,opt,name=Query" json:"Query,omitempty"`
	Slices      []uint64 `protobuf:"varint,2,rep,packed,name=Slices" json:"Slices,omitempty"`
	ColumnAttrs bool     `protobuf:"varint,3,opt,name=ColumnAttrs" json:"ColumnAttrs,omitempty"`
	Remote      bool     `protobuf:"varint,5,opt,name=Remote" json:"Remote,omitempty"`
}

func (m *QueryRequest) Reset()                    { *m = QueryRequest{} }
func (m *QueryRequest) String() string            { return proto.CompactTextString(m) }
func (*QueryRequest) ProtoMessage()               {}
func (*QueryRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *QueryRequest) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

func (m *QueryRequest) GetSlices() []uint64 {
	if m != nil {
		return m.Slices
	}
	return nil
}

func (m *QueryRequest) GetColumnAttrs() bool {
	if m != nil {
		return m.ColumnAttrs
	}
	return false
}

func (m *QueryRequest) GetRemote() bool {
	if m != nil {
		return m.Remote
	}
	return false
}

type QueryResponse struct {
	Err            string           `protobuf:"bytes,1,opt,name=Err" json:"Err,omitempty"`
	Results        []*QueryResult   `protobuf:"bytes,2,rep,name=Results" json:"Results,omitempty"`
	ColumnAttrSets []*ColumnAttrSet `protobuf:"bytes,3,rep,name=ColumnAttrSets" json:"ColumnAttrSets,omitempty"`
}

func (m *QueryResponse) Reset()                    { *m = QueryResponse{} }
func (m *QueryResponse) String() string            { return proto.CompactTextString(m) }
func (*QueryResponse) ProtoMessage()               {}
func (*QueryResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *QueryResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func (m *QueryResponse) GetResults() []*QueryResult {
	if m != nil {
		return m.Results
	}
	return nil
}

func (m *QueryResponse) GetColumnAttrSets() []*ColumnAttrSet {
	if m != nil {
		return m.ColumnAttrSets
	}
	return nil
}

type QueryResult struct {
	Bitmap  *Bitmap `protobuf:"bytes,1,opt,name=Bitmap" json:"Bitmap,omitempty"`
	N       uint64  `protobuf:"varint,2,opt,name=N" json:"N,omitempty"`
	Pairs   []*Pair `protobuf:"bytes,3,rep,name=Pairs" json:"Pairs,omitempty"`
	Changed bool    `protobuf:"varint,4,opt,name=Changed" json:"Changed,omitempty"`
}

func (m *QueryResult) Reset()                    { *m = QueryResult{} }
func (m *QueryResult) String() string            { return proto.CompactTextString(m) }
func (*QueryResult) ProtoMessage()               {}
func (*QueryResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *QueryResult) GetBitmap() *Bitmap {
	if m != nil {
		return m.Bitmap
	}
	return nil
}

func (m *QueryResult) GetN() uint64 {
	if m != nil {
		return m.N
	}
	return 0
}

func (m *QueryResult) GetPairs() []*Pair {
	if m != nil {
		return m.Pairs
	}
	return nil
}

func (m *QueryResult) GetChanged() bool {
	if m != nil {
		return m.Changed
	}
	return false
}

type ImportRequest struct {
	Index      string   `protobuf:"bytes,1,opt,name=Index" json:"Index,omitempty"`
	Frame      string   `protobuf:"bytes,2,opt,name=Frame" json:"Frame,omitempty"`
	Slice      uint64   `protobuf:"varint,3,opt,name=Slice" json:"Slice,omitempty"`
	RowIDs     []uint64 `protobuf:"varint,4,rep,packed,name=RowIDs" json:"RowIDs,omitempty"`
	ColumnIDs  []uint64 `protobuf:"varint,5,rep,packed,name=ColumnIDs" json:"ColumnIDs,omitempty"`
	Timestamps []int64  `protobuf:"varint,6,rep,packed,name=Timestamps" json:"Timestamps,omitempty"`
	View       string   `protobuf:"bytes,7,opt,name=View" json:"View,omitempty"`
}

func (m *ImportRequest) Reset()                    { *m = ImportRequest{} }
func (m *ImportRequest) String() string            { return proto.CompactTextString(m) }
func (*ImportRequest) ProtoMessage()               {}
func (*ImportRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *ImportRequest) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

func (m *ImportRequest) GetFrame() string {
	if m != nil {
		return m.Frame
	}
	return ""
}

func (m *ImportRequest) GetSlice() uint64 {
	if m != nil {
		return m.Slice
	}
	return 0
}

func (m *ImportRequest) GetRowIDs() []uint64 {
	if m != nil {
		return m.RowIDs
	}
	return nil
}

func (m *ImportRequest) GetColumnIDs() []uint64 {
	if m != nil {
		return m.ColumnIDs
	}
	return nil
}

func (m *ImportRequest) GetTimestamps() []int64 {
	if m != nil {
		return m.Timestamps
	}
	return nil
}

func (m *ImportRequest) GetView() string {
	if m != nil {
		return m.View
	}
	return ""
}

func init() {
	proto.RegisterType((*Bitmap)(nil), "internal.Bitmap")
	proto.RegisterType((*Pair)(nil), "internal.Pair")
	proto.RegisterType((*Bit)(nil), "internal.Bit")
	proto.RegisterType((*ColumnAttrSet)(nil), "internal.ColumnAttrSet")
	proto.RegisterType((*Attr)(nil), "internal.Attr")
	proto.RegisterType((*AttrMap)(nil), "internal.AttrMap")
	proto.RegisterType((*QueryRequest)(nil), "internal.QueryRequest")
	proto.RegisterType((*QueryResponse)(nil), "internal.QueryResponse")
	proto.RegisterType((*QueryResult)(nil), "internal.QueryResult")
	proto.RegisterType((*ImportRequest)(nil), "internal.ImportRequest")
}

func init() { proto.RegisterFile("internal/public.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 553 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0xdb, 0x6e, 0xd4, 0x30,
	0x10, 0x95, 0x37, 0xd9, 0xdb, 0x6c, 0x77, 0x55, 0x59, 0x14, 0x22, 0x84, 0x50, 0x14, 0xf1, 0x90,
	0xa7, 0x5d, 0xa9, 0x7c, 0x00, 0x62, 0x2f, 0x95, 0x22, 0x44, 0x05, 0xb3, 0xa5, 0xef, 0x69, 0x6b,
	0x95, 0x48, 0xb9, 0x61, 0x3b, 0x94, 0xfd, 0x00, 0xbe, 0x80, 0x9f, 0xe0, 0x1f, 0xf8, 0x39, 0x34,
	0x76, 0xbc, 0x49, 0x79, 0x40, 0x7d, 0xf3, 0x39, 0xe3, 0x71, 0xe6, 0xcc, 0x99, 0x09, 0x9c, 0x65,
	0xa5, 0x16, 0xb2, 0x4c, 0xf3, 0x55, 0xdd, 0xdc, 0xe4, 0xd9, 0xed, 0xb2, 0x96, 0x95, 0xae, 0xf8,
	0xc4, 0xd1, 0xd1, 0x1a, 0x46, 0xeb, 0x4c, 0x17, 0x69, 0xcd, 0x39, 0xf8, 0xeb, 0x4c, 0xab, 0x80,
	0x85, 0x5e, 0xec, 0xa3, 0x39, 0xf3, 0x37, 0x30, 0x7c, 0xaf, 0xb5, 0x54, 0xc1, 0x20, 0xf4, 0xe2,
	0xd9, 0xf9, 0x62, 0xe9, 0xf2, 0x96, 0x44, 0xa3, 0x0d, 0x46, 0x4b, 0xf0, 0x3f, 0xa5, 0x99, 0xe4,
	0xa7, 0xe0, 0x7d, 0x10, 0x87, 0x80, 0x85, 0x2c, 0xf6, 0x91, 0x8e, 0xfc, 0x19, 0x0c, 0x37, 0x55,
	0x53, 0xea, 0x60, 0x60, 0x38, 0x0b, 0xa2, 0x2f, 0xe0, 0xad, 0x33, 0x4d, 0x41, 0xac, 0x1e, 0x92,
	0x6d, 0x9b, 0x60, 0x01, 0x7f, 0x09, 0x93, 0x4d, 0x95, 0x37, 0x45, 0x99, 0x6c, 0xdb, 0xac, 0x23,
	0xe6, 0xaf, 0x60, 0x7a, 0x95, 0x15, 0x42, 0xe9, 0xb4, 0xa8, 0x03, 0x2f, 0x64, 0xb1, 0x87, 0x1d,
	0x11, 0xed, 0x60, 0x6e, 0x6f, 0x52, 0x55, 0x7b, 0xa1, 0xf9, 0x02, 0x06, 0xc7, 0xd7, 0x07, 0xc9,
	0xf6, 0x89, 0x6a, 0x7e, 0x33, 0xf0, 0xe9, 0xd4, 0x97, 0x33, 0xb5, 0x72, 0x38, 0xf8, 0x57, 0x87,
	0x5a, 0xb4, 0x75, 0x99, 0x33, 0x0f, 0x61, 0xb6, 0xd7, 0x32, 0x2b, 0xef, 0xaf, 0xd3, 0xbc, 0x11,
	0xa6, 0xaa, 0x29, 0xf6, 0x29, 0x52, 0x94, 0x94, 0xda, 0x86, 0x7d, 0x53, 0xf4, 0x11, 0x93, 0xa2,
	0x75, 0x55, 0xe5, 0x36, 0x38, 0x0c, 0x59, 0x3c, 0xc1, 0x8e, 0xe0, 0xaf, 0x01, 0x2e, 0xf2, 0x2a,
	0x6d, 0x73, 0x47, 0x21, 0x8b, 0x19, 0xf6, 0x98, 0x68, 0x05, 0x63, 0xaa, 0xf4, 0x63, 0x5a, 0x77,
	0xda, 0xd8, 0xff, 0xb4, 0x7d, 0x87, 0x93, 0xcf, 0x8d, 0x90, 0x07, 0x14, 0xdf, 0x1a, 0xa1, 0x8c,
	0x05, 0x06, 0xb7, 0x22, 0x2d, 0xe0, 0xcf, 0x61, 0xb4, 0xcf, 0xb3, 0x5b, 0x61, 0x1b, 0xe5, 0x63,
	0x8b, 0x48, 0x6a, 0xd7, 0x60, 0x65, 0xa4, 0x4e, 0xb0, 0x4f, 0x51, 0x26, 0x8a, 0xa2, 0xd2, 0x4e,
	0x4b, 0x8b, 0xa2, 0x5f, 0x0c, 0xe6, 0xed, 0x87, 0x55, 0x5d, 0x95, 0x4a, 0x50, 0x73, 0x77, 0x52,
	0xba, 0xe6, 0xee, 0xa4, 0xe4, 0x2b, 0x18, 0xa3, 0x50, 0x4d, 0xae, 0x9d, 0x3f, 0x67, 0x9d, 0x06,
	0x97, 0xdb, 0xe4, 0x1a, 0xdd, 0x2d, 0xfe, 0x0e, 0x16, 0x8f, 0xfc, 0xa6, 0x8a, 0x28, 0xef, 0x45,
	0x97, 0xf7, 0x28, 0x8e, 0xff, 0x5c, 0x8f, 0x7e, 0x32, 0x98, 0xf5, 0x5e, 0xe6, 0xb1, 0xdb, 0x05,
	0x53, 0xd6, 0xec, 0xfc, 0xb4, 0x7b, 0xc8, 0xf2, 0xe8, 0x76, 0xe5, 0x04, 0xd8, 0x65, 0x3b, 0x05,
	0xec, 0x92, 0x7a, 0x4f, 0xf3, 0xef, 0xbe, 0xdf, 0xeb, 0x3d, 0xd1, 0x68, 0x83, 0x3c, 0x80, 0xf1,
	0xe6, 0x6b, 0x5a, 0xde, 0x8b, 0x3b, 0x33, 0x05, 0x13, 0x74, 0x30, 0xfa, 0xc3, 0x60, 0x9e, 0x14,
	0x75, 0x25, 0x75, 0xcf, 0x97, 0xa4, 0xbc, 0x13, 0x3f, 0x9c, 0x2f, 0x06, 0x10, 0x7b, 0x21, 0xd3,
	0xc2, 0xce, 0xdf, 0x14, 0x2d, 0x20, 0xd6, 0xf8, 0x63, 0xfc, 0xf0, 0xd1, 0x02, 0xe3, 0x04, 0xed,
	0x93, 0x0a, 0x7c, 0xeb, 0xa1, 0x45, 0x34, 0x70, 0x6e, 0x9d, 0x54, 0x30, 0x34, 0xa1, 0x8e, 0xa0,
	0x81, 0x3b, 0xee, 0x93, 0x0a, 0x46, 0xa1, 0x17, 0x7b, 0xd8, 0x63, 0x68, 0x01, 0xae, 0x33, 0xf1,
	0x10, 0x8c, 0x4d, 0x01, 0xe6, 0x7c, 0x33, 0x32, 0xbf, 0x94, 0xb7, 0x7f, 0x03, 0x00, 0x00, 0xff,
	0xff, 0x70, 0x51, 0x61, 0x8b, 0x6b, 0x04, 0x00, 0x00,
}
