// Code generated by protoc-gen-go.
// source: internal/public.proto
// DO NOT EDIT!

/*
Package internal is a generated protocol buffer package.

It is generated from these files:
	internal/public.proto

It has these top-level messages:
	Bitmap
	Pair
	SumCount
	Bit
	ColumnAttrSet
	Attr
	AttrMap
	QueryRequest
	QueryResponse
	QueryResult
	ImportRequest
	ImportValueRequest
*/
package internal

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Bitmap struct {
	Bits  []uint64 `protobuf:"varint,1,rep,packed,name=Bits" json:"Bits,omitempty"`
	Attrs []*Attr  `protobuf:"bytes,2,rep,name=Attrs" json:"Attrs,omitempty"`
}

func (m *Bitmap) Reset()                    { *m = Bitmap{} }
func (m *Bitmap) String() string            { return proto.CompactTextString(m) }
func (*Bitmap) ProtoMessage()               {}
func (*Bitmap) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Bitmap) GetAttrs() []*Attr {
	if m != nil {
		return m.Attrs
	}
	return nil
}

type Pair struct {
	Key   uint64 `protobuf:"varint,1,opt,name=Key" json:"Key,omitempty"`
	Count uint64 `protobuf:"varint,2,opt,name=Count" json:"Count,omitempty"`
}

func (m *Pair) Reset()                    { *m = Pair{} }
func (m *Pair) String() string            { return proto.CompactTextString(m) }
func (*Pair) ProtoMessage()               {}
func (*Pair) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type SumCount struct {
	Sum   int64 `protobuf:"varint,1,opt,name=Sum" json:"Sum,omitempty"`
	Count int64 `protobuf:"varint,2,opt,name=Count" json:"Count,omitempty"`
}

func (m *SumCount) Reset()                    { *m = SumCount{} }
func (m *SumCount) String() string            { return proto.CompactTextString(m) }
func (*SumCount) ProtoMessage()               {}
func (*SumCount) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type Bit struct {
	RowID     uint64 `protobuf:"varint,1,opt,name=RowID" json:"RowID,omitempty"`
	ColumnID  uint64 `protobuf:"varint,2,opt,name=ColumnID" json:"ColumnID,omitempty"`
	Timestamp int64  `protobuf:"varint,3,opt,name=Timestamp" json:"Timestamp,omitempty"`
}

func (m *Bit) Reset()                    { *m = Bit{} }
func (m *Bit) String() string            { return proto.CompactTextString(m) }
func (*Bit) ProtoMessage()               {}
func (*Bit) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type ColumnAttrSet struct {
	ID    uint64  `protobuf:"varint,1,opt,name=ID" json:"ID,omitempty"`
	Attrs []*Attr `protobuf:"bytes,2,rep,name=Attrs" json:"Attrs,omitempty"`
}

func (m *ColumnAttrSet) Reset()                    { *m = ColumnAttrSet{} }
func (m *ColumnAttrSet) String() string            { return proto.CompactTextString(m) }
func (*ColumnAttrSet) ProtoMessage()               {}
func (*ColumnAttrSet) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ColumnAttrSet) GetAttrs() []*Attr {
	if m != nil {
		return m.Attrs
	}
	return nil
}

type Attr struct {
	Key         string  `protobuf:"bytes,1,opt,name=Key" json:"Key,omitempty"`
	Type        uint64  `protobuf:"varint,2,opt,name=Type" json:"Type,omitempty"`
	StringValue string  `protobuf:"bytes,3,opt,name=StringValue" json:"StringValue,omitempty"`
	IntValue    int64   `protobuf:"varint,4,opt,name=IntValue" json:"IntValue,omitempty"`
	BoolValue   bool    `protobuf:"varint,5,opt,name=BoolValue" json:"BoolValue,omitempty"`
	FloatValue  float64 `protobuf:"fixed64,6,opt,name=FloatValue" json:"FloatValue,omitempty"`
}

func (m *Attr) Reset()                    { *m = Attr{} }
func (m *Attr) String() string            { return proto.CompactTextString(m) }
func (*Attr) ProtoMessage()               {}
func (*Attr) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type AttrMap struct {
	Attrs []*Attr `protobuf:"bytes,1,rep,name=Attrs" json:"Attrs,omitempty"`
}

func (m *AttrMap) Reset()                    { *m = AttrMap{} }
func (m *AttrMap) String() string            { return proto.CompactTextString(m) }
func (*AttrMap) ProtoMessage()               {}
func (*AttrMap) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *AttrMap) GetAttrs() []*Attr {
	if m != nil {
		return m.Attrs
	}
	return nil
}

type QueryRequest struct {
	Query        string   `protobuf:"bytes,1,opt,name=Query" json:"Query,omitempty"`
	Slices       []uint64 `protobuf:"varint,2,rep,packed,name=Slices" json:"Slices,omitempty"`
	ColumnAttrs  bool     `protobuf:"varint,3,opt,name=ColumnAttrs" json:"ColumnAttrs,omitempty"`
	Remote       bool     `protobuf:"varint,5,opt,name=Remote" json:"Remote,omitempty"`
	ExcludeAttrs bool     `protobuf:"varint,6,opt,name=ExcludeAttrs" json:"ExcludeAttrs,omitempty"`
	ExcludeBits  bool     `protobuf:"varint,7,opt,name=ExcludeBits" json:"ExcludeBits,omitempty"`
}

func (m *QueryRequest) Reset()                    { *m = QueryRequest{} }
func (m *QueryRequest) String() string            { return proto.CompactTextString(m) }
func (*QueryRequest) ProtoMessage()               {}
func (*QueryRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type QueryResponse struct {
	Err            string           `protobuf:"bytes,1,opt,name=Err" json:"Err,omitempty"`
	Results        []*QueryResult   `protobuf:"bytes,2,rep,name=Results" json:"Results,omitempty"`
	ColumnAttrSets []*ColumnAttrSet `protobuf:"bytes,3,rep,name=ColumnAttrSets" json:"ColumnAttrSets,omitempty"`
}

func (m *QueryResponse) Reset()                    { *m = QueryResponse{} }
func (m *QueryResponse) String() string            { return proto.CompactTextString(m) }
func (*QueryResponse) ProtoMessage()               {}
func (*QueryResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *QueryResponse) GetResults() []*QueryResult {
	if m != nil {
		return m.Results
	}
	return nil
}

func (m *QueryResponse) GetColumnAttrSets() []*ColumnAttrSet {
	if m != nil {
		return m.ColumnAttrSets
	}
	return nil
}

type QueryResult struct {
	Bitmap   *Bitmap   `protobuf:"bytes,1,opt,name=Bitmap" json:"Bitmap,omitempty"`
	N        uint64    `protobuf:"varint,2,opt,name=N" json:"N,omitempty"`
	Pairs    []*Pair   `protobuf:"bytes,3,rep,name=Pairs" json:"Pairs,omitempty"`
	SumCount *SumCount `protobuf:"bytes,5,opt,name=SumCount" json:"SumCount,omitempty"`
	Changed  bool      `protobuf:"varint,4,opt,name=Changed" json:"Changed,omitempty"`
}

func (m *QueryResult) Reset()                    { *m = QueryResult{} }
func (m *QueryResult) String() string            { return proto.CompactTextString(m) }
func (*QueryResult) ProtoMessage()               {}
func (*QueryResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *QueryResult) GetBitmap() *Bitmap {
	if m != nil {
		return m.Bitmap
	}
	return nil
}

func (m *QueryResult) GetPairs() []*Pair {
	if m != nil {
		return m.Pairs
	}
	return nil
}

func (m *QueryResult) GetSumCount() *SumCount {
	if m != nil {
		return m.SumCount
	}
	return nil
}

type ImportRequest struct {
	Index      string   `protobuf:"bytes,1,opt,name=Index" json:"Index,omitempty"`
	Frame      string   `protobuf:"bytes,2,opt,name=Frame" json:"Frame,omitempty"`
	Slice      uint64   `protobuf:"varint,3,opt,name=Slice" json:"Slice,omitempty"`
	RowIDs     []uint64 `protobuf:"varint,4,rep,packed,name=RowIDs" json:"RowIDs,omitempty"`
	ColumnIDs  []uint64 `protobuf:"varint,5,rep,packed,name=ColumnIDs" json:"ColumnIDs,omitempty"`
	Timestamps []int64  `protobuf:"varint,6,rep,packed,name=Timestamps" json:"Timestamps,omitempty"`
}

func (m *ImportRequest) Reset()                    { *m = ImportRequest{} }
func (m *ImportRequest) String() string            { return proto.CompactTextString(m) }
func (*ImportRequest) ProtoMessage()               {}
func (*ImportRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

type ImportValueRequest struct {
	Index     string   `protobuf:"bytes,1,opt,name=Index" json:"Index,omitempty"`
	Frame     string   `protobuf:"bytes,2,opt,name=Frame" json:"Frame,omitempty"`
	Slice     uint64   `protobuf:"varint,3,opt,name=Slice" json:"Slice,omitempty"`
	Field     string   `protobuf:"bytes,4,opt,name=Field" json:"Field,omitempty"`
	ColumnIDs []uint64 `protobuf:"varint,5,rep,packed,name=ColumnIDs" json:"ColumnIDs,omitempty"`
	Values    []uint64 `protobuf:"varint,6,rep,packed,name=Values" json:"Values,omitempty"`
}

func (m *ImportValueRequest) Reset()                    { *m = ImportValueRequest{} }
func (m *ImportValueRequest) String() string            { return proto.CompactTextString(m) }
func (*ImportValueRequest) ProtoMessage()               {}
func (*ImportValueRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func init() {
	proto.RegisterType((*Bitmap)(nil), "internal.Bitmap")
	proto.RegisterType((*Pair)(nil), "internal.Pair")
	proto.RegisterType((*SumCount)(nil), "internal.SumCount")
	proto.RegisterType((*Bit)(nil), "internal.Bit")
	proto.RegisterType((*ColumnAttrSet)(nil), "internal.ColumnAttrSet")
	proto.RegisterType((*Attr)(nil), "internal.Attr")
	proto.RegisterType((*AttrMap)(nil), "internal.AttrMap")
	proto.RegisterType((*QueryRequest)(nil), "internal.QueryRequest")
	proto.RegisterType((*QueryResponse)(nil), "internal.QueryResponse")
	proto.RegisterType((*QueryResult)(nil), "internal.QueryResult")
	proto.RegisterType((*ImportRequest)(nil), "internal.ImportRequest")
	proto.RegisterType((*ImportValueRequest)(nil), "internal.ImportValueRequest")
}

func init() { proto.RegisterFile("internal/public.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 631 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xac, 0x54, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xd6, 0xc6, 0x8e, 0xe3, 0x4c, 0xda, 0xaa, 0x5a, 0xd1, 0x62, 0x21, 0x84, 0x2c, 0x8b, 0x83,
	0x4f, 0xa9, 0x14, 0x1e, 0x00, 0x91, 0x36, 0x95, 0x2c, 0x44, 0x05, 0x9b, 0xc2, 0xdd, 0x4d, 0x56,
	0xc5, 0x92, 0xff, 0x58, 0xaf, 0x45, 0xf3, 0x1c, 0xbc, 0x01, 0x17, 0x78, 0x01, 0x6e, 0x3c, 0x1c,
	0x9a, 0x59, 0x6f, 0xec, 0x70, 0x00, 0x0e, 0xdc, 0xf6, 0xfb, 0xe6, 0xc7, 0xf3, 0xf3, 0x8d, 0xe1,
	0x2c, 0x2b, 0xb5, 0x54, 0x65, 0x9a, 0x5f, 0xd4, 0xed, 0x5d, 0x9e, 0x6d, 0xe6, 0xb5, 0xaa, 0x74,
	0xc5, 0x7d, 0x4b, 0x47, 0x4b, 0xf0, 0x96, 0x99, 0x2e, 0xd2, 0x9a, 0x73, 0x70, 0x97, 0x99, 0x6e,
	0x02, 0x16, 0x3a, 0xb1, 0x2b, 0xe8, 0xcd, 0x9f, 0xc3, 0xf8, 0x95, 0xd6, 0xaa, 0x09, 0x46, 0xa1,
	0x13, 0xcf, 0x16, 0x27, 0x73, 0x1b, 0x37, 0x47, 0x5a, 0x18, 0x63, 0x34, 0x07, 0xf7, 0x6d, 0x9a,
	0x29, 0x7e, 0x0a, 0xce, 0x6b, 0xb9, 0x0b, 0x58, 0xc8, 0x62, 0x57, 0xe0, 0x93, 0x3f, 0x82, 0xf1,
	0x65, 0xd5, 0x96, 0x3a, 0x18, 0x11, 0x67, 0x40, 0xb4, 0x00, 0x7f, 0xdd, 0x16, 0xf4, 0xc6, 0x98,
	0x75, 0x5b, 0x50, 0x8c, 0x23, 0xf0, 0x79, 0x18, 0xe3, 0xd8, 0x98, 0xf7, 0xe0, 0x2c, 0x33, 0x8d,
	0x46, 0x51, 0x7d, 0x4e, 0xae, 0xba, 0x8f, 0x18, 0xc0, 0x9f, 0x80, 0x7f, 0x59, 0xe5, 0x6d, 0x51,
	0x26, 0x57, 0xdd, 0x97, 0xf6, 0x98, 0x3f, 0x85, 0xe9, 0x6d, 0x56, 0xc8, 0x46, 0xa7, 0x45, 0x1d,
	0x38, 0x94, 0xb2, 0x27, 0xa2, 0x15, 0x1c, 0x1b, 0x4f, 0xec, 0x64, 0x2d, 0x35, 0x3f, 0x81, 0xd1,
	0x3e, 0xfb, 0x28, 0xb9, 0xfa, 0xc7, 0x09, 0x7c, 0x67, 0xe0, 0xe2, 0x6b, 0x38, 0x82, 0xa9, 0x19,
	0x01, 0x07, 0xf7, 0x76, 0x57, 0xcb, 0xae, 0x2e, 0x7a, 0xf3, 0x10, 0x66, 0x6b, 0xad, 0xb2, 0xf2,
	0xfe, 0x43, 0x9a, 0xb7, 0x92, 0xaa, 0x9a, 0x8a, 0x21, 0x85, 0x1d, 0x25, 0xa5, 0x36, 0x66, 0x97,
	0x8a, 0xde, 0x63, 0xec, 0x68, 0x59, 0x55, 0xb9, 0x31, 0x8e, 0x43, 0x16, 0xfb, 0xa2, 0x27, 0xf8,
	0x33, 0x80, 0xeb, 0xbc, 0x4a, 0xbb, 0x58, 0x2f, 0x64, 0x31, 0x13, 0x03, 0x26, 0xba, 0x80, 0x09,
	0x56, 0xfa, 0x26, 0xad, 0xfb, 0xde, 0xd8, 0x9f, 0x7a, 0xfb, 0xc9, 0xe0, 0xe8, 0x5d, 0x2b, 0xd5,
	0x4e, 0xc8, 0x4f, 0xad, 0x6c, 0x68, 0x07, 0x84, 0xbb, 0x2e, 0x0d, 0xe0, 0xe7, 0xe0, 0xad, 0xf3,
	0x6c, 0x23, 0xcd, 0xa4, 0x5c, 0xd1, 0x21, 0xec, 0xb5, 0x9f, 0x70, 0x43, 0xbd, 0xfa, 0x62, 0x48,
	0x61, 0xa4, 0x90, 0x45, 0xa5, 0x6d, 0x33, 0x1d, 0xe2, 0x11, 0x1c, 0xad, 0x1e, 0x36, 0x79, 0xbb,
	0x95, 0x26, 0xd4, 0x23, 0xeb, 0x01, 0x87, 0xd9, 0x3b, 0x4c, 0xda, 0x9d, 0x98, 0xec, 0x03, 0x2a,
	0xfa, 0xc2, 0xe0, 0xb8, 0x2b, 0xbf, 0xa9, 0xab, 0xb2, 0x91, 0xb8, 0xa3, 0x95, 0x52, 0x76, 0x47,
	0x2b, 0xa5, 0xf8, 0x05, 0x4c, 0x84, 0x6c, 0xda, 0x5c, 0xdb, 0x35, 0x9f, 0xf5, 0xa3, 0xb0, 0xb1,
	0x6d, 0xae, 0x85, 0xf5, 0xe2, 0x2f, 0xe1, 0xe4, 0x40, 0x36, 0xd8, 0x17, 0xc6, 0x3d, 0xee, 0xe3,
	0x0e, 0xec, 0xe2, 0x37, 0xf7, 0xe8, 0x07, 0x83, 0xd9, 0x20, 0x33, 0x8f, 0xed, 0x19, 0x52, 0x59,
	0xb3, 0xc5, 0x69, 0x9f, 0xc8, 0xf0, 0xc2, 0x9e, 0xe9, 0x11, 0xb0, 0x9b, 0x4e, 0x4c, 0xec, 0x06,
	0x57, 0x88, 0xa7, 0x67, 0xbf, 0x3f, 0x58, 0x21, 0xd2, 0xc2, 0x18, 0xf9, 0xbc, 0x3f, 0x38, 0x9a,
	0xf1, 0x6c, 0xc1, 0x7b, 0x47, 0x6b, 0x11, 0xfd, 0x51, 0x06, 0x30, 0xb9, 0xfc, 0x98, 0x96, 0xf7,
	0x72, 0x4b, 0xe2, 0xf3, 0x85, 0x85, 0xd1, 0x37, 0x06, 0xc7, 0x49, 0x51, 0x57, 0x4a, 0x0f, 0xd4,
	0x90, 0x94, 0x5b, 0xf9, 0x60, 0xd5, 0x40, 0x00, 0xd9, 0x6b, 0x95, 0x16, 0x46, 0xf6, 0x53, 0x61,
	0x00, 0xb2, 0xa4, 0x0a, 0x52, 0x81, 0x2b, 0x0c, 0xa0, 0xfd, 0xe3, 0x19, 0x37, 0x81, 0x6b, 0x94,
	0x63, 0x10, 0xea, 0xdc, 0x5e, 0x71, 0x13, 0x8c, 0xc9, 0xd4, 0x13, 0xa8, 0xf3, 0xfd, 0x19, 0xa3,
	0x36, 0x9c, 0xd8, 0x11, 0x03, 0x26, 0xfa, 0xca, 0x80, 0x9b, 0x4a, 0x49, 0xf7, 0xff, 0xaf, 0x5c,
	0xf4, 0xcd, 0x64, 0x6e, 0x46, 0x83, 0xbe, 0x08, 0xfe, 0x52, 0xec, 0x39, 0x78, 0x54, 0x85, 0x29,
	0xd4, 0x15, 0x1d, 0xba, 0xf3, 0xe8, 0x77, 0xfc, 0xe2, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb6,
	0xf6, 0x9b, 0xb5, 0xa7, 0x05, 0x00, 0x00,
}
